目录

一、Python基础

- 列表与推导式
- 匿名函数与map  
- zip与enumerate
    
二、Numpy

- 数组的构造
- - 疑问
- 数组的变形与合并    
- 数组的切片与索引
- 常用函数
- 广播机制
- 向量与矩阵的计算

# 一、Python基础

## 1、列表与推导式

In [21]:
#定义一个列表
L = []

#定义一个函数
def my_func(x):
    return 2 * x

#使用append将数字序列添加到列表中
#range代表0，1，2，3，4
for i in range(5):
    L.append(my_func(i))
    
#打印L
print(L)

#简化
print([my_func(i) for i in range(5)])

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


In [25]:
#多层嵌套
print([name + ' likes ' + fruit for name in ['Mike', 'Amy'] for fruit in ['apple', 'banana']])

['Mike likes apple', 'Mike likes banana', 'Amy likes apple', 'Amy likes banana']


In [28]:
#if选择条件赋值
value = 'cat' if 2 > 1 else 'dog'
print(value)

#等价
a, b = 'cat', 'dog'
condition = 2 > 1
if condition:
    value = a
else:
    value = b
print(value)

cat
cat


In [29]:
#大于5的用5代替
L = [1, 2, 5, 7, 9]
print([i if i <= 5 else 5 for i in L])

[1, 2, 5, 5, 5]


## 2、匿名函数与map方法

In [30]:
#匿名函数
my_func = lambda x: 2*x
print(my_func(3))

multi_para_func = lambda a, b: a + b
print(multi_para_func(1, 2))

6
3


In [31]:
#不关心函数名字
print([(lambda x: 2*x)(i) for i in range(5)])

[0, 2, 4, 6, 8]


In [34]:
#使用map函数完成匿名函数的映射，返回值为map对象
print( type(map(lambda x: 2*x, range(5))) )

#转为list
print( list(map(lambda x: 2*x, range(5))) )

<class 'map'>
[0, 2, 4, 6, 8]


In [35]:
#多个输入值的函数映射
print(list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde'))))

['0_a', '1_b', '2_c', '3_d', '4_e']


## 3、 zip对象与enumerate方法

In [39]:
#zip函数把多个可迭代对象打包成一个元组构成的可迭代对象，返回一个zip对象
L1, L2, L3 = list('abc'), list('def'), list('hij')

#通过tuple, list可以得到相应的打包结果
print(list(zip(L1, L2, L3)),'\n')
print(tuple(zip(L1, L2, L3)),'\n')

#循环迭代
for i, j, k in zip(L1, L2, L3):
     print(i, j, k)

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')] 

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')) 

a d h
b e i
c f j


In [43]:
#enumerate在迭代时绑定迭代元素的遍历序号：
L = list('abcd')
for index, value in enumerate(L):
     print(index, value)

print('\n')
for value in enumerate(L):
     print(value)

0 a
1 b
2 c
3 d


(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


In [44]:
#用zip对象实现这个功能：
for index, value in zip(range(len(L)), L):
     print(index, value)

0 a
1 b
2 c
3 d


In [45]:
#对两个列表建立字典映射时，可以利用zip对象：
print(dict(zip(L1, L2)))

{'a': 'd', 'b': 'e', 'c': 'f'}


In [47]:
#压缩
zipped = list(zip(L1, L2, L3))
print(zipped)

#前面加上*解压
# 三个元组分别对应原来的列表
print(list(zip(*zipped)))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]


# 二、numpy基础

## 1. np数组的构造

In [51]:
#通过array来构造：
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [53]:
#等差序列：np.linspace, np.arange
print(np.linspace(1,5,4)) # 起始、终止（包含）、样本个数

print(np.arange(1,5,2)) # 起始、终止（不包含）、步长

[1.         2.33333333 3.66666667 5.        ]
[1 3]


In [57]:
#特殊矩阵：zeros, eye, full

print('zero\n',np.zeros((2,3))) # 维度大小:2行3列

print('eye\n',np.eye(3)) # 3*3的单位矩阵

print('eye\n',np.eye(3, k=1)) # 偏移主对角线1个单位的伪单位矩阵

print('full\n',np.full((2,3), 10)) # 2行3列，10表示填充数值

print('full\n',np.full((2,3), [1,2,3])) # 2行3列，每行填入相同的列表


zero
 [[0. 0. 0.]
 [0. 0. 0.]]
eye
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eye
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
full
 [[10 10 10]
 [10 10 10]]
full
 [[1 2 3]
 [1 2 3]]


In [58]:
#随机矩阵：np.random

In [60]:
#rand(x)：0-1均匀分布的随机数组
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.67364481, 0.44505125, 0.82345719])

In [61]:
#rand(x,y)：标准正态的随机数组
np.random.rand(3, 3) # 3行3列

array([[0.21122415, 0.32824675, 0.27073278],
       [0.33321727, 0.62830276, 0.36453297],
       [0.83589933, 0.22230049, 0.04559062]])

In [71]:
#区间a到b上的均匀分布
a, b = 5, 15
print((b - a) * np.random.rand(3) + a)

#使用uniform函数
print(np.random.uniform(5, 15, 3))

[14.09501592  7.98098633  6.79740609]
[ 9.95392228  9.53241604 12.54637615]


In [72]:
#randn生成了N(0,I)的标准正态分布：
np.random.randn(3)

array([-0.01221442, -0.34035264,  1.74088235])

In [73]:
np.random.randn(2, 2)

array([[ 0.31743304, -0.35421853],
       [ 0.02254583, -0.62574491]])

In [75]:
#服从方差为𝜎2均值为𝜇的一元正态分布
sigma, mu = 2.5, 3
print(mu + np.random.randn(3) * sigma)

#使用normal函数
print(np.random.normal(3, 2.5, 3))

[ 0.71894969  3.00917229 -2.9243073 ]
[-0.13612663  5.32875794  1.26449601]


In [79]:
#randint：随机整数
print(np.random.randint(3))

#指定指定生成随机整数的最小值最大值（不包含）和维度大小：
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
print(np.random.randint(low, high, size))

2
[[11 12]
 [14  7]]


In [85]:
#choice：随机列表抽样,默认抽取方式为有放回抽样
print(np.random.choice(3),'\n')

#从给定的列表中，以一定概率和方式抽取结果
my_list = ['a', 'b', 'c', 'd']
print(np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1]),'\n')

#不指定概率时为均匀采样
print(np.random.choice(my_list, (3,3)))

0 

['c' 'b'] 

[['c' 'c' 'd']
 ['c' 'c' 'c']
 ['c' 'a' 'd']]


In [87]:
#打散原列表
print(np.random.choice(my_list, 4, replace=False, p=[0.25, 0.25, 0.25, 0.25]),'\n')

#使用permutation函数
print(np.random.permutation(my_list))

['c' 'd' 'b' 'a'] 

['c' 'd' 'a' 'b']


In [88]:
#随机种子，固定随机数的输出结果：
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [89]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [90]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [91]:
np.random.seed(1)
np.random.rand()

0.417022004702574

## 2. np数组的变形与合并

In [94]:
#转置：T
print(np.zeros((2,3)),'\n')
print(np.zeros((2,3)).T)

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [97]:
#二维数组
#r_ 上下合并
print(np.r_[np.zeros((2,3)),np.zeros((2,3))],'\n')

#c_ 左右合并
print(np.c_[np.zeros((2,3)),np.zeros((2,3))])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [111]:
#一维数组和二维数组进行合并时，应当把其视作列向量，在长度匹配的情况下只能够使用左右合并的c_操作：
try:
     np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
     Err_Msg = e
print(Err_Msg,'\n')

all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) 



In [117]:
print(np.array([0,0]),'\n')

print(np.zeros(2),'\n')

print(np.r_[np.array([0,0]),np.zeros(2)],'\n')

print(np.c_[np.array([0,0]),np.zeros(2)],'\n')

[0 0] 

[0. 0.] 

[0. 0. 0. 0.] 

[[0. 0.]
 [0. 0.]] 



In [115]:
print(np.array([0,0]),'\n')

print(np.zeros((2,3)),'\n')

print(np.c_[np.array([0,0]),np.zeros((2,3))])

[0 0] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [116]:
print(np.r_[np.array([0,0]),np.zeros((2,3))])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

# 疑问

In [127]:
#r_ 上下合并
print(np.r_[np.zeros((1,2)),np.zeros((1,2))],'\n')

print(np.r_[np.array([0,0]),np.zeros(2)])

[[0. 0.]
 [0. 0.]] 

[0. 0. 0. 0.]


In [129]:
#c_ 左右合并
print(np.c_[np.zeros((1,2)),np.zeros((1,2))],'\n')

print(np.c_[np.array([0,0]),np.zeros(2)])

[[0. 0. 0. 0.]] 

[[0. 0.]
 [0. 0.]]


In [135]:
np.zeros((1,2)).shape

(1, 2)

In [176]:
#长得像行向量的列向量
print(np.array([0,0]),'\n',np.zeros(2))

[0 0] 
 [0. 0.]


In [136]:
np.array([0,0]).shape

(2,)

In [137]:
np.zeros(2).shape

(2,)

In [175]:
c = np.r_[np.array([0,0]),np.zeros(2)]
c.shape

(4,)

![01](./01.jpg)

In [140]:
#维度变换：reshape:把原数组按照新的维度重新排列。

target = np.arange(8).reshape(2,4)
print(target,'\n')

#C模式,按照行读取和填充(默认)
print(target.reshape((4,2), order='C'),'\n') 

#F模式,按照列读取和填充
print(target.reshape((4,2), order='F'),'\n')

#数组的大小是确定的，reshape允许有一个维度存在空缺，此时只需填充-1即可：
print(target.reshape((4,-1)))

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 2]
 [4 6]
 [1 3]
 [5 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [143]:
#常用操作
target = np.ones((3,1))
print(target,'\n')

print(target.reshape(-1))

[[1.]
 [1.]
 [1.]] 

[1. 1. 1.]


## 3. np数组的切片与索引

In [147]:
#数组的切片模式支持使用slice类型的start:end:step切片，还可以直接传入列表指定某个维度的索引进行切片：
target = np.arange(9).reshape(3,3)
print(target,'\n')

print(target[:-1, [0,2]],'\n')

#此外，还可以利用np.ix_在对应的维度上使用布尔索引，但此时不能使用slice切片：
print(target[np.ix_([True, False, True], [True, False, True])],'\n')

print(target[np.ix_([1,2], [True, False, True])],'\n')

#当数组维度为1维时，可以直接进行布尔索引，而无需np.ix_：
new = target.reshape(-1)
print(new[new%2==0])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 2]
 [3 5]] 

[[0 2]
 [6 8]] 

[[3 5]
 [6 8]] 

[0 2 4 6 8]


## 4. 常用函数

In [149]:
#where: 指定满足条件与不满足条件位置对应的填充值：
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5) # 对应位置为True时填充a对应元素，否则填充5

array([5, 1, 5, 5])

In [150]:
#返回索引
#nonzero返回非零数的索
a = np.array([-2,-5,0,1,3,-1])
print(np.nonzero(a))

#argmax返回最大值的索引
print(a.argmax())

#argmin返回最小值的索引：
print(a.argmin())

(array([0, 1, 3, 4, 5], dtype=int64),)
4
1


In [151]:
#any指当序列至少 存在一个 True或非零元素时返回True，否则返回False
a = np.array([0,1])
print(a.any())

#all指当序列元素 全为 True或非零元素时返回True，否则返回False
print(a.all())

True
False


In [153]:
#cumprod累乘函数
a = np.array([1,2,4])
print(a.cumprod())

#cumsum累加函数
print(a.cumsum())

#diff表示和前一个元素做差，由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1
print(np.diff(a))

[1 2 8]
[1 3 7]
[1 2]


In [155]:
#统计函数
#常用的统计函数包括max, min, mean, median, std, var, sum, quantile
target = np.arange(5)
print(target)

print(target.max())

#分位数计算是全局方法，因此不能通过array.quantile的方法调用：
print(np.quantile(target, 0.5)) # 0.5分位数

[0 1 2 3 4]
4
2.0


In [157]:
target = np.array([1, 2, np.nan])
print(target)

#对于含有缺失值的数组，它们返回的结果也是缺失值
print(target.max())

#略过缺失值，必须使用nan*类型的函数
print(np.nanmax(target))

#上述的几个统计函数都有对应的nan*函数。
print(np.nanquantile(target, 0.5))

[ 1.  2. nan]
nan
2.0
1.5


In [158]:
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])

#协方差cov
print(np.cov(target1, target2),'\n')

#相关系数corrcoef
print(np.corrcoef(target1, target2))

[[ 11.66666667 -16.66666667]
 [-16.66666667  38.66666667]]
[[ 1.         -0.78470603]
 [-0.78470603  1.        ]]


In [160]:
#axis参数，
target = np.arange(1,10).reshape(3,-1)
print(target,'\n')

#axis=0时，按列统计
print(target.sum(0),'\n')

#axis=1时，按行统计
print(target.sum(1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18] 

[ 6 15 24]


## 5. 广播机制

In [161]:
#广播机制用于处理两个不同维度数组之间的操作

#标量和数组的操作
#标量会自动把大小扩充为数组大小，之后进行逐元素操作：

res = 3 * np.ones((2,2)) + 1
print(res)

res = 1 / res
print(res)

[[4. 4.]
 [4. 4.]]
[[0.25 0.25]
 [0.25 0.25]]


In [164]:
#二维数组之间的操作
#当两个数组维度完全一致时，使用对应元素的操作，否则会报错，
res = np.ones((3,2))
print(res)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [165]:
#除非其中的某个数组的维度是𝑚×1或者1×𝑛，那么会扩充其具有1的维度为另一个数组对应维度的大小。
#例如，1×2数组和3×2数组做逐元素运算时会把第一个数组扩充为3×2，扩充时的对应数值进行赋值。
#但是，需要注意的是，如果第一个数组的维度是1×3，那么由于在第二维上的大小不匹配且不为1，此时报错。

print(res * np.array([[2,3]])) # 第二个数组扩充第一维度为3

[[2. 3.]
 [2. 3.]
 [2. 3.]]


In [166]:
print(res * np.array([[2],[3],[4]])) # 第二个数组扩充第二维度为2

[[2. 2.]
 [3. 3.]
 [4. 4.]]


In [167]:
print(res * np.array([[2]])) # 等价于两次扩充，第二个数组两个维度分别扩充为3和2

[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [168]:
#一维数组与二维数组的操作

#当一维数组𝐴𝑘与二维数组𝐵𝑚,𝑛操作时，等价于把一维数组视作𝐴1,𝑘的二维数组，使用的广播法则与【b】中一致，当𝑘!=𝑛且𝑘,𝑛都不是1时报错。

np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [169]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [170]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

## 6. 向量与矩阵的计算

In [171]:
#向量内积：dot
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)
#1*1+2*3+3*5

22

向量范数和矩阵范数：np.linalg.norm

在矩阵范数的计算中，最重要的是ord参数，可选值如下：

| ord | norm for matrices | norm for vectors |
| :---- | ----: | ----: |
| None   | Frobenius norm | 2-norm |
| 'fro'  | Frobenius norm  | / |
| 'nuc'  | nuclear norm    | / |
| inf    | max(sum(abs(x), axis=1))   | max(abs(x)) |
| -inf   | min(sum(abs(x), axis=1))  |  min(abs(x)) |
| 0      | /   |  sum(x != 0) |
| 1      | max(sum(abs(x), axis=0))  |  as below |
| -1     | min(sum(abs(x), axis=0))   |  as below |
| 2      | 2-norm (largest sing. value) | as below |
| -2     | smallest singular value    | as below |
| other  | /   | sum(abs(x)\*\*ord)\*\*(1./ord) |



In [177]:
matrix_target =  np.arange(4).reshape(-1,2)
print(matrix_target)

print(np.linalg.norm(matrix_target, 'fro'))

print(np.linalg.norm(matrix_target, np.inf))

print(np.linalg.norm(matrix_target, 2))

[[0 1]
 [2 3]]
3.7416573867739413
5.0
3.702459173643833


In [178]:
vector_target =  np.arange(4)
print(vector_target)

print(np.linalg.norm(vector_target, np.inf))

print(np.linalg.norm(vector_target, 2))

print(np.linalg.norm(vector_target, 3))

[0 1 2 3]
3.0
3.7416573867739413
3.3019272488946263


In [179]:
#矩阵乘法：@
a = np.arange(4).reshape(-1,2)
print(a)

b = np.arange(-4,0).reshape(-1,2)
print(b)

print(a@b)

[[0 1]
 [2 3]]
[[-4 -3]
 [-2 -1]]
[[ -2  -1]
 [-14  -9]]


## 三、练习

In [180]:
#Ex1：利用列表推导式写矩阵乘法
#一般的矩阵乘法根据公式，可以由三重循环写出，请将其改写为列表推导式的形式。

M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

In [194]:
np.random.seed(0)
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
print(M1,'\n\n',M1,'\n')

res = [[sum([M1[i][k] * M2[k][j] 
             for k in range(M1.shape[1])
            ]) 
        for j in range(M2.shape[1])
       ] 
       for i in range(M1.shape[0])
      ]

print(M1@M2,'\n\n',res)

(np.abs((M1@M2 - res) < 1e-15)).all()

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]] 

 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]] 

[[0.84920503 0.92019544 0.94731748 1.37428751]
 [0.6197338  0.76625728 0.77879738 1.13884855]] 

 [[0.8492050332765654, 0.9201954386455283, 0.9473174754148058, 1.3742875058416857], [0.6197337964575249, 0.7662572840289622, 0.7787973807055315, 1.1388485499974779]]


True

### Ex2：更新矩阵
设矩阵 $A_{m×n}$ ，现在对 $A$ 中的每一个元素进行更新生成矩阵 $B$ ，更新方法是 $B_{ij}=A_{ij}\sum_{k=1}^n\frac{1}{A_{ik}}$ ，例如下面的矩阵为 $A$ ，则 $B_{2,2}=5\times(\frac{1}{4}+\frac{1}{5}+\frac{1}{6})=\frac{37}{12}$ ，请利用 `Numpy` 高效实现。
$$\begin{split}A=\left[ \begin{matrix} 1 & 2 &3\\4&5&6\\7&8&9 \end{matrix} \right]\end{split}$$

In [204]:
A = np.arange(1,10).reshape(3,-1)
print(A,'\n')
print(1/A,'\n')
print((1/A).sum(1),'\n')
print((1/A).sum(1).reshape(-1,1),'\n')

B = A*(1/A).sum(1).reshape(-1,1)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]] 

[1.83333333 0.61666667 0.37896825] 

[[1.83333333]
 [0.61666667]
 [0.37896825]] 

[[1.83333333 3.66666667 5.5       ]
 [2.46666667 3.08333333 3.7       ]
 [2.65277778 3.03174603 3.41071429]]


### Ex3：卡方统计量

设矩阵$A_{m\times n}$，记$B_{ij} = \frac{(\sum_{i=1}^mA_{ij})\times (\sum_{j=1}^nA_{ij})}{\sum_{i=1}^m\sum_{j=1}^nA_{ij}}$，定义卡方值如下：
$$\chi^2 = \sum_{i=1}^m\sum_{j=1}^n\frac{(A_{ij}-B_{ij})^2}{B_{ij}}$$
请利用`Numpy`对给定的矩阵$A$计算$\chi^2$ 

In [216]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
print(A,'\n')

print(A.sum(0),'\n')#按列求和
print(A.sum(1).reshape(-1,1),'\n')#按行求和
print(A.sum(),'\n')

B = (A.sum(1).reshape(-1,1) * A.sum(0)) / A.sum()
print(B,'\n')

print(((A - B) ** 2 / B).sum())

[[15 10 13 13 17]
 [19 13 15 12 14]
 [17 16 18 18 11]
 [16 17 17 18 11]
 [15 19 18 19 14]
 [13 10 13 15 10]
 [12 13 18 11 13]
 [13 13 17 10 11]] 

[120 111 129 116 101] 

[[68]
 [73]
 [80]
 [79]
 [85]
 [61]
 [67]
 [64]] 

577 

[[14.14211438 13.08145581 15.20277296 13.67071057 11.90294627]
 [15.18197574 14.04332756 16.32062392 14.67590988 12.77816291]
 [16.63778163 15.38994801 17.88561525 16.08318891 14.0034662 ]
 [16.42980936 15.19757366 17.66204506 15.88214905 13.82842288]
 [17.67764298 16.35181976 19.0034662  17.08838821 14.87868284]
 [12.68630849 11.73483536 13.63778163 12.26343154 10.67764298]
 [13.93414211 12.88908146 14.97920277 13.46967071 11.72790295]
 [13.3102253  12.31195841 14.3084922  12.86655113 11.20277296]] 

11.842696601945802


### Ex4：改进矩阵计算的性能
设$Z$为$m×n$的矩阵，$B$和$U$分别是$m×p$和$p×n$的矩阵，$B_i$为$B$的第$i$行，$U_j$为$U$的第$j$列，下面定义$\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n\|B_i-U_j\|_2^2Z_{ij}$，其中$\|\mathbf{a}\|_2^2$表示向量$a$的分量平方和$\sum_i a_i^2$。

现有某人根据如下给定的样例数据计算$R$的值，请充分利用`Numpy`中的函数，基于此问题改进这段代码的性能。

In [217]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

令 $Y_{ij} = \|B_i-U_j\|_2^2$，则 $\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n Y_{ij}Z_{ij}$
 ，这在 Numpy 中可以用逐元素的乘法后求和实现，因此问题转化为了如何构造 $Y$ 矩阵。
$$
\begin{split}Y_{ij} &= \|B_i-U_j\|_2^2\\
&=\sum_{k=1}^p(B_{ik}-U_{kj})^2\\
&=\sum_{k=1}^p B_{ik}^2+\sum_{k=1}^p U_{kj}^2-2\sum_{k=1}^p B_{ik}U_{kj}\\\end{split}
$$
 
从上式可以看出，第一第二项分别为 $B$ 的行平方和与 $U$ 的列平方和，第三项是两倍的内积。因此，$Y$  矩阵可以写为三个部分，第一个部分是 $m\times n$ 的全 $1$ 矩阵每行乘以 $B$ 对应行的行平方和，第二个部分是相同大小的全 $1$ 矩阵每列乘以 $U$ 对应列的列平方和，第三个部分恰为 $B$ 矩阵与 $U$ 矩阵乘积的两倍。从而结果如下：

In [223]:
(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum()

100566

In [228]:
print(B**2,'\n')

print((B**2).sum(1),'\n')

print((B**2).sum(1).reshape(-1,1),'\n')

print((U**2),'\n')

print((U**2).sum(0),'\n')

print(2*B@U,'\n')

print(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z,'\n')

print((((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum(),'\n')

[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]] 

[30 26 26 19 23 28 32 28 27 23 21 27 25 28 26 22 27 27 24 15 21 25 24 26
 22 29 27 31 30 25 27 25 27 24 25 24 21 28 25 29 24 22 24 25 25 25 33 27
 25 25 29 21 28 31 24 26 26 24 32 28 22 27 31 27 24 20 23 25 25 29 20 22
 24 29 27 23 30 20 25 24 26 26 26 15 29 30 31 30 28 30 24 16 25 20 26 28
 20 23 28 23] 

[[30]
 [26]
 [26]
 [19]
 [23]
 [28]
 [32]
 [28]
 [27]
 [23]
 [21]
 [27]
 [25]
 [28]
 [26]
 [22]
 [27]
 [27]
 [24]
 [15]
 [21]
 [25]
 [24]
 [26]
 [22]
 [29]
 [27]
 [31]
 [30]
 [25]
 [27]
 [25]
 [27]
 [24]
 [25]
 [24]
 [21]
 [28]
 [25]
 [29]
 [24]
 [22]
 [24]
 [25]
 [25]
 [25]
 [33]
 [27]
 [25]
 [25]
 [29]
 [21]
 [28]
 [31]
 [24]
 [26]
 [26]
 [24]
 [32]
 [28]
 [22]
 [27]
 [31]
 [27]
 [24]
 [20]
 [23]
 [25]
 [25]
 [29]
 [20]
 [22]
 [24]
 [29]
 [27]
 [23]
 [30]
 [20]
 [25]
 [24]
 [26]
 [26]
 [26]
 [15]
 [29]
 [30]
 [31]
 [30]
 [28]
 [30]
 [24]
 [16]
 [25]
 [20]
 [26]


In [ ]:
#性能

In [224]:
%timeit -n 30 solution(B, U, Z)

59.8 ms ± 5.03 ms per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [225]:
%timeit -n 30 ((np.ones((m,n))*(B**2).sum(1).reshape(-1,1) +\
                  np.ones((m,n))*(U**2).sum(0) - 2*B@U)*Z).sum()

884 µs ± 197 µs per loop (mean ± std. dev. of 7 runs, 30 loops each)


### Ex5：连续整数的最大长度

输入一个整数的`Numpy`数组，返回其中严格递增连续整数子数组的最大长度，正向是指递增方向。例如，输入\[1,2,5,6,7\]，\[5,6,7\]为具有最大长度的连续整数子数组，因此输出3；输入\[3,2,1,2,3,4,6\]，\[1,2,3,4\]为具有最大长度的连续整数子数组，因此输出4。请充分利用`Numpy`的内置函数完成。（提示：考虑使用`nonzero, diff`函数）

In [218]:
f = lambda x:np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()

f([1,2,5,6,7])

3

In [222]:
x = [1,2,5,6,7]

print(np.diff(x)!=1)#diff返回差值

print(np.r_[1,np.diff(x)!=1,1])

print(np.nonzero(np.r_[1,np.diff(x)!=1,1]))#nonzero返回非零索引

print(np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])))

[False  True False False]
[1 0 1 0 0 1]
(array([0, 2, 5], dtype=int64),)
[[2 3]]
