In [ ]:
不会写，好难啊

In [1]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

##### 注意
在补充习题中不得使用任何for循环。

# Ex1：NumPy的向量化运算
### 1、
给定一个正整数列表，请找出缺失的最小正整数。

In [375]:
def get_miss(nums): 
    nums = np.where(nums > 0, nums, len(nums) + 1) #将小于等于0的值替换为  列表长度+1
    
    nums = list(set(nums))#删除重复值
    
    nums.sort()#排序

    b = list(np.array(range(1,len(nums)+1)))#正整数列表1，2，3，。。。

    v = list(map(lambda x: x[0]-x[1], zip(b, nums)))#对应元素相减 b-nums

    num_zero = np.where(v,0,1).sum()#统计0的个数（等于0替换为1，不等于0则替换为0，sum求和）

    return num_zero + 1


arr = np.array([5,2,1,0,4])
get_miss(arr)   

3

In [54]:
def get_miss(nums):    
    nums = list(set(nums))#删除重复值
    n = len(nums)#列表长度
    j = 0
    while(1):
        if j > n - 1: #判断有没有超出表长
            break
        if nums[j] <= 0:
            nums[j] = n + 1 #将小于等于0的值替换为n+1
        j = j + 1

    nums.sort()#排序
    i = 0
    while(1):
        if i > n - 1: #i超出表长，则答案是n+1
            return n + 1
        if nums[i] != i + 1: #第i个位置上的值与i+1不相等，则答案为i+1
            return i + 1
        i = i + 1

In [55]:
arr = np.array([1])
get_miss(arr)

2

In [56]:
arr = np.array([2,3,4])
get_miss(arr)

1

In [57]:
arr = np.array([6,3,5,1,2])
get_miss(arr)

4

In [58]:
arr = np.array([5,2,1,3,4])
get_miss(arr)

6

### 2、
设计一个生成二维NumPy数组的函数get_res()，其输入为正整数n，返回的数组构造方式如下：第1行填入1个1，第2行在上一行填入位置的下一列连续填入2个2，第3行在第二行最后一个填入位置的下一列连续填入3个3，…，第n行在第n-1行最后一个填入位置的下一列连续填入n个n。

###### 思路
- 第一步
$$A = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix} * \begin{pmatrix} 1 & 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 & 1 \\ 1 & 1 & 1 & 1 & 1 & 1 \end{pmatrix} = \begin{pmatrix} 1 & 1 & 1 & 1 & 1 & 1 \\ 2 & 2 & 2 & 2 & 2 & 2 \\ 3 & 3 & 3 & 3 & 3 & 3 \end{pmatrix}$$

- 第二步
$$L1 = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix} * \begin{pmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{pmatrix} = \begin{pmatrix} 1 & 1 & 1 \\ 2 & 2 & 2 \\ 3 & 3 & 3 \end{pmatrix} ， L2 = L1的转置 = \begin{pmatrix} 1 & 2 & 3 \\ 1 & 2 & 3 \\ 1 & 2 & 3 \end{pmatrix}$$

$$L1 小于 L2则取0，其余不变，where实现 = \begin{pmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 3 & 3 & 3 \end{pmatrix}$$

$$转为一维，L3 = \begin{pmatrix} 1 & 0 & 0 & 2 & 2 & 0 & 3 & 3 & 3 \end{pmatrix}$$

$$逆序，L4 = \begin{pmatrix} 3 & 3 & 3 & 2 & 2 & 1 & 0 & 0 & 0  \end{pmatrix}$$

$$切片后排序，L5 = \begin{pmatrix} 1 & 2 & 2 & 3 & 3 & 3 \end{pmatrix}$$

$$L5 * n然后reshape = B = \begin{pmatrix} 1 & 2 & 2 & 3 & 3 & 3 \\ 1 & 2 & 2 & 3 & 3 & 3 \\ 1 & 2 & 2 & 3 & 3 & 3 \end{pmatrix}$$

- 第三步
$$ A 与 B 相同则保留，否则取0,where实现 = \begin{pmatrix} 1 & 0 & 0 & 0 & 0 & 0 \\ 0 & 2 & 2 & 0 & 0 & 0 \\ 0 & 0 & 0 & 3 & 3 & 3  \end{pmatrix} $$

In [494]:
def get_res(n):
    m = np.array(range(n+1)).sum()#列数
    r1 = np.ones((n,m))#生成m*n的全1矩阵
    r = np.array(range(1,n+1)).reshape((n,-1))#生成1到n的列向量
    A = r * r1
    #print(A)

    #生成1 2 2 3 3 3 4 4 4 4.....的序列
    L = np.array(range(1,n+1))
    L1 = L*np.ones((n,n))
    L2 = L1.T#生成第i行全为i+1的矩阵

    L3 = np.where(L1 > L2, 0, L2)#把右上部分变为0
    L3 = L3.reshape(-1)

    L4 = L3.tolist()
    L4.sort(reverse=True)

    m = np.array(range(n+1)).sum()
    L5 = L4[:m]#去掉0元素
    L5.sort()

    B = np.array(L5*n).reshape((n,-1))
    #print(B)

    res = np.where(A == B, A, 0)
    return res

In [495]:
n = 5
get_res(n)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 3., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 4., 4., 4., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 5., 5., 5., 5.]])

In [204]:
def get_res(n):
    i = 0   
    h = n#行数
    m = np.array(range(n+1)).sum()#列数
    res = []
    while(n):
        a = list(np.zeros(np.array(range(i+1)).sum()))#数字前面的0
        b = list((i+1)*np.ones(i+1))#数字
        c = list(np.zeros(m - len(a) - len(b)))#数字后面的0
        res.extend(a)#拼接
        res.extend(b)
        res.extend(c)
        i = i + 1
        n = n - 1

    res = np.array(res).reshape((h,m))
    return res

In [205]:
n = 4
get_res(n)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 3., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 4., 4., 4., 4.]])

### 3、
点 $A$ 初始位置在数轴原点处，现进行n步简单随机游走，即每一步以等概率向左或向右移动长度为1的距离，记该点最终的位置为 $S_n$ ，则可以证明
$$\lim_{n\rightarrow+\infty}\frac{\mathbb{E}|S_n|}{\sqrt{n}}=\sqrt{\frac{2}{\pi}}$$
 
 
 
现取n为5000进行1000次试验，且每次试验中用 $\frac{1}{100}\sum_{k=1}^{100}|S_n|$
 
 来代替 $\mathbb{E}|S_n|$ 。此时可以计算得到1000个 $\mathbb{E}|S_n|$
 
 
 的估计值，请计算这些估计值的均值、0.05分位数和0.95分位数。

In [257]:
np.random.seed(1)
move = np.random.choice([-1,1], 5000)#-1表示左移，1表示右移
move

array([ 1,  1, -1, ..., -1,  1, -1])

In [258]:
Sn = move.sum()
Sn

-52

In [542]:
def ESn():
    j = 1000
    b = [0] * 1000

    while(j):
        i = 100
        a = [0] * 100
        np.random.seed(j)
        while(i):
            i = i - 1
            a[i] = np.random.choice([-1,1], 5000).sum()
            #print(a)
        j = j - 1
        b[j] = np.array(a).sum()
        #print(b[j])
    return b


In [548]:
df = pd.DataFrame(data = {'ESn': ESn()})

df

ESn
0     632
1      20
2    -630
3     996
4     240
..    ...
995  -126
996   942
997   604
998  -352
999 -1692

[1000 rows x 1 columns]

In [549]:
df_demo = df[['ESn']]

df_demo.mean()

ESn    13.192
dtype: float64

In [550]:
df_demo.quantile(0.05)

ESn   -1123.1
Name: 0.05, dtype: float64

In [551]:
df_demo.quantile(0.95)

ESn    1158.3
Name: 0.95, dtype: float64

### 4、
在二维平面上有n个点，每个点具有k维特征，点的坐标数据记录在node_xy中，点的特征数据记录在node_fea中。现要计算所有点的相关矩阵 $S$ ，点a和点b的相关系数定义如下
$$S_{ab} = \frac{\sigma_{ab}}{2} + \frac{\lambda_{ab}}{2}$$
 
 
其中，若记点a特征为 $A$ ，点b特征为 $B$ ，则有
$$\sigma_{ab} = \frac{\sum_{i=1}^kA_iB_i}{\sqrt{\sum_{i=1}^kA^2_i}\sqrt{\sum_{i=1}^kB^2_i}}$$
 
对于点a而言，将所有点到点a的二维平面距离进行排序，从而得到每个点到点a的距离排名，距离最近（排名为1）的点是点a自身，记点b的排名为 $r^{(a)}_b$
 ，则定义
$$\lambda_{ab} = 1 - \frac{2\times (r^{(a)}_b-1)}{n-1}$$
 
请对于给定的node_xy和node_fea计算相关矩阵 $S$ 。（提示：使用np.argsort()）

In [655]:
np.array([1,2,3])*np.array([2,3,4])

array([ 2,  6, 12])

In [568]:
a1 = (node_fea * node_fea).sum(0) ** 0.5
a1

array([18.56189011, 18.60935879, 18.20188555, 18.25688122, 18.48384902,
       17.65103939, 18.00270978, 18.73917192, 18.28816958, 18.31893988])

In [57]:
def sigma_ab(node_fea):
    a = n
    
    sigmaab = [[0] * n] * n
    while(a):
        a = a - 1
        b = n
        while(b):
            b = b - 1
            d1 = (node_fea[a] * node_fea[b]).sum()
           
            d2 = ((node_fea[a] ** 2.0).sum(0) ** 0.5) * ((node_fea[b] ** 2.0).sum(0) ** 0.5)
            sigmaab[a][b] = d1/d2
    #print(type(sigmaab))
    #print(sigmaab)
            #sigmaab[a][b] = np.array(d1 / d2)
    return sigmaab

In [184]:
def lambda_ab(node_xy):
    a = n
#     d3 = [[0] * n] * n
    m=n*n
    d3 = list(np.zeros(m).reshape((n,-1)))
    d4 = [0]
#     d4 = [0] * n
    lambdaab = [[0] * n] * n
    while(a):
        a = a - 1
        b = n
        while(b):
            b = b - 1
            d3[a][b] = ((node_xy[a][0] - node_xy[b][0]) ** 2 + (node_xy[a][1] - node_xy[b][1]) ** 2) ** 0.5#距离
            print('d3[',a,'][',b,']=',d3[a][b])
    print(type(d3))
    print(d3)
    d4[a] = np.argsort(d3,axis=1)#按行排序，返回索引,即排名=索引+1  #这个排序有问题

    print(type(d4))
    print(d4)
    lambdaab[a][b] = 1 - ((2  / (n - 1))* np.array(d4))
    #print(type(lambdaab))
    #print(lambdaab)
    return lambdaab

In [185]:
def get_S(node_xy, node_fea):
    S = np.array(sigma_ab(node_fea)) *0.5 + np.array(lambda_ab(node_xy)) *0.5
    return S

In [186]:
n, k = 5, 2
np.random.seed(1)
node_xy = np.random.rand(n, 2)
node_fea = np.random.rand(n, k)
get_S(node_xy, node_fea)

d3[ 4 ][ 4 ]= 0.0
d3[ 4 ][ 3 ]= 0.2857642243880516
d3[ 4 ][ 2 ]= 0.5117113645946397
d3[ 4 ][ 1 ]= 0.4617991336650459
d3[ 4 ][ 0 ]= 0.18263436900301927
d3[ 3 ][ 4 ]= 0.2857642243880516
d3[ 3 ][ 3 ]= 0.0
d3[ 3 ][ 2 ]= 0.25628507489994234
d3[ 3 ][ 1 ]= 0.19109930874428313
d3[ 3 ][ 0 ]= 0.44011235595489956
d3[ 2 ][ 4 ]= 0.5117113645946397
d3[ 2 ][ 3 ]= 0.25628507489994234
d3[ 2 ][ 2 ]= 0.0
d3[ 2 ][ 1 ]= 0.25612732176293496
d3[ 2 ][ 0 ]= 0.683673943665646
d3[ 1 ][ 4 ]= 0.4617991336650459
d3[ 1 ][ 3 ]= 0.19109930874428313
d3[ 1 ][ 2 ]= 0.25612732176293496
d3[ 1 ][ 1 ]= 0.0
d3[ 1 ][ 0 ]= 0.5903636317721634
d3[ 0 ][ 4 ]= 0.18263436900301927
d3[ 0 ][ 3 ]= 0.44011235595489956
d3[ 0 ][ 2 ]= 0.683673943665646
d3[ 0 ][ 1 ]= 0.5903636317721634
d3[ 0 ][ 0 ]= 0.0
<class 'list'>
[array([0.        , 0.59036363, 0.68367394, 0.44011236, 0.18263437]), array([0.59036363, 0.        , 0.25612732, 0.19109931, 0.46179913]), array([0.68367394, 0.25612732, 0.        , 0.25628507, 0.51171136]), array([0.44011236, 

<ipython-input-185-8840ced702aa>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  S = np.array(sigma_ab(node_fea)) *0.5 + np.array(lambda_ab(node_xy)) *0.5


array([[array([[[1.  , 0.  , 0.25, 0.75, 0.5 ],
        [0.75, 0.25, 0.5 , 0.  , 1.  ],
        [0.5 , 0.75, 0.25, 0.  , 1.  ],
        [0.25, 0.75, 0.5 , 0.  , 1.  ],
        [0.  , 1.  , 0.25, 0.75, 0.5 ]]]),
        0.47457492312980126, 0.4368107040275298, 0.49786201084805026,
        0.49886174328271676],
       [array([[[1.  , 0.  , 0.25, 0.75, 0.5 ],
        [0.75, 0.25, 0.5 , 0.  , 1.  ],
        [0.5 , 0.75, 0.25, 0.  , 1.  ],
        [0.25, 0.75, 0.5 , 0.  , 1.  ],
        [0.  , 1.  , 0.25, 0.75, 0.5 ]]]),
        0.47457492312980126, 0.4368107040275298, 0.49786201084805026,
        0.49886174328271676],
       [array([[[1.  , 0.  , 0.25, 0.75, 0.5 ],
        [0.75, 0.25, 0.5 , 0.  , 1.  ],
        [0.5 , 0.75, 0.25, 0.  , 1.  ],
        [0.25, 0.75, 0.5 , 0.  , 1.  ],
        [0.  , 1.  , 0.25, 0.75, 0.5 ]]]),
        0.47457492312980126, 0.4368107040275298, 0.49786201084805026,
        0.49886174328271676],
       [array([[[1.  , 0.  , 0.25, 0.75, 0.5 ],
        [0.75, 0.25

###### d4的输出结果看着不对，不知道哪里有问题

# Ex2：统计学生的成绩情况
在data/supplement/ex2目录下存放了某校高三第一学期的学生成绩情况，包含16次周测成绩、期中考试成绩和期末考试成绩，科目一栏的成绩表示学生选课的成绩。所有的表中，相同的行表示的是同一位同学。请完成以下练习：

In [227]:
df = pd.read_csv('data/supplement/ex2/第1次周测成绩.csv')

df.head()

班级   姓名  选科   语文  数学   英语  科目
0   1   吴刚  地理   93  95   82  69
1   1   卢楠  物理  108  77   90  94
2   1  唐秀兰  历史   88  72   95  85
3   1   张刚  化学   85  88  102  76
4   1   姜洋  历史  104  99   84  86

### 1、
该校高三年级中是否存在姓名相同的学生？

In [ ]:
没有

In [311]:
test_df = pd.read_csv('data/supplement/ex2/第1次周测成绩.csv')
df1=test_df.groupby(["姓名"]).size()
df1

姓名
丁帅     1
丁斌     1
丁燕     1
万云     1
万志强    1
      ..
龙晨     1
龙秀荣    1
龙鑫     1
龙雪梅    1
龚建华    1
Length: 896, dtype: int64

In [312]:
col=df1[df1>1].reset_index()[["姓名"]] #查看重复次数
col

Empty DataFrame
Columns: [姓名]
Index: []

In [313]:
df11 = pd.merge(col,test_df,on=["姓名"])
print(df11)

Empty DataFrame
Columns: [班级, 姓名, 选科, 语文, 数学, 英语, 科目]
Index: []


### 2、
在第一次周测中，请求出每个班级选修物理或化学同学的语数英总分的平均值。哪个班级最高？

In [277]:
df.head()

班级   姓名  选科   语文  数学   英语  科目
0   1   吴刚  地理   93  95   82  69
1   1   卢楠  物理  108  77   90  94
2   1  唐秀兰  历史   88  72   95  85
3   1   张刚  化学   85  88  102  76
4   1   姜洋  历史  104  99   84  86

In [314]:
df2 = df.query('(选科 == ["物理", "化学"] )')
# df2.index
# df2.values
df2

班级   姓名  选科   语文   数学   英语   科目
1     1   卢楠  物理  108   77   90   94
3     1   张刚  化学   85   88  102   76
7     1  张秀云  物理  100   98   90   90
12    1   陈柳  化学  117   58   86   83
15    1   葛丽  物理  118   65  108   67
..   ..  ...  ..  ...  ...  ...  ...
886  11   蔡兵  物理   98   61   83  106
888  11   刘柳  物理   97  116   82   88
889  11   宋龙  化学   94   75   64   79
894  11   夏刚  化学   99   82   77   80
895  11  权玉珍  物理  108   77   78   82

[377 rows x 7 columns]

In [315]:
sum = df2.语文+df2.数学+df2.英语
sum

1      275
3      275
7      288
12     261
15     291
      ... 
886    242
888    295
889    233
894    258
895    263
Length: 377, dtype: int64

In [316]:
df3 = pd.DataFrame(data = {'班级': df2.班级, '姓名':df2.姓名,
                          '语数英总分': list(df2.语文+df2.数学+df2.英语)},
                  index = df2.index)


df3

班级   姓名  语数英总分
1     1   卢楠    275
3     1   张刚    275
7     1  张秀云    288
12    1   陈柳    261
15    1   葛丽    291
..   ..  ...    ...
886  11   蔡兵    242
888  11   刘柳    295
889  11   宋龙    233
894  11   夏刚    258
895  11  权玉珍    263

[377 rows x 3 columns]

In [317]:
condition = ["班级"]
df4 = df3.groupby(condition)["语数英总分"].mean()
df4

班级
1     274.727273
2     281.818182
3     269.794118
4     265.522727
5     268.676471
6     272.894737
7     270.818182
8     268.162162
9     270.071429
10    268.675676
11    262.076923
Name: 语数英总分, dtype: float64

In [308]:
df4.max()

281.8181818181818

In [319]:
col=df4[df4==df4.max()].reset_index()[["班级"]] #查看重复次数
col

班级
0   2

### 3、
学生在该学期的总评计算方式是各次考试总分的加权平均值，其中周测成绩权重为50%（每次测验权重相等，即3.125%），期中权重为20%，期末权重为30%。请结合nlargest函数找出年级中总评前十的同学。

In [365]:
df_s = pd.read_csv('data/supplement/ex2/第1次周测成绩.csv')#读取表格
df_s1=df_s.copy()
df_s1.insert(loc=7, column='加权', value=list((df_s1.语文+df_s1.数学+df_s1.英语+df_s1.科目)*0.03125))

df_s1

班级   姓名  选科   语文  数学   英语  科目        加权
0     1   吴刚  地理   93  95   82  69  10.59375
1     1   卢楠  物理  108  77   90  94  11.53125
2     1  唐秀兰  历史   88  72   95  85  10.62500
3     1   张刚  化学   85  88  102  76  10.96875
4     1   姜洋  历史  104  99   84  86  11.65625
..   ..  ...  ..  ...  ..  ...  ..       ...
891  11  申建国  历史   85  60   98  80  10.09375
892  11   裴勇  历史  118  95   94  72  11.84375
893  11   王文  历史   92  71   87  62   9.75000
894  11   夏刚  化学   99  82   77  80  10.56250
895  11  权玉珍  物理  108  77   78  82  10.78125

[896 rows x 8 columns]

In [342]:
col_1=df_s1["加权"] #
col_1

0      10.59375
1      11.53125
2      10.62500
3      10.96875
4      11.65625
         ...   
891    10.09375
892    11.84375
893     9.75000
894    10.56250
895    10.78125
Name: 加权, Length: 896, dtype: float64

In [359]:
ss = ['data/supplement/ex2/第1次周测成绩.csv',
      'data/supplement/ex2/第2次周测成绩.csv',
     'data/supplement/ex2/第3次周测成绩.csv',
     'data/supplement/ex2/第4次周测成绩.csv',
     'data/supplement/ex2/第5次周测成绩.csv',
     'data/supplement/ex2/第6次周测成绩.csv',
     'data/supplement/ex2/第7次周测成绩.csv',
     'data/supplement/ex2/第8次周测成绩.csv',
     'data/supplement/ex2/第9次周测成绩.csv',
     'data/supplement/ex2/第10次周测成绩.csv',
     'data/supplement/ex2/第11次周测成绩.csv',
     'data/supplement/ex2/第12次周测成绩.csv',
     'data/supplement/ex2/第13次周测成绩.csv',
     'data/supplement/ex2/第14次周测成绩.csv',
     'data/supplement/ex2/第15次周测成绩.csv',
     'data/supplement/ex2/第16次周测成绩.csv',
     'data/supplement/ex2/期末考试成绩.csv',
     'data/supplement/ex2/期中考试成绩.csv']

In [362]:
def zcj():
    n = 16
    sc = np.zeros(896)
    while(n):
        n = n - 1
        df = pd.read_csv(ss[n])#读取表格
        sc = sc + (df.语文+df.数学+df.英语+df.科目)*0.03125
    
    df1 = pd.read_csv(ss[17])
    sc1 = (df1.语文+df1.数学+df1.英语+df1.科目)*0.2
    df2 = pd.read_csv(ss[16])
    sc2 = (df2.语文+df2.数学+df2.英语+df2.科目)*0.3
    sc = sc + sc1 + sc2
    
    return sc

zcj()

0      371.94375
1      395.54375
2      391.28125
3      395.83125
4      381.65000
         ...    
891    376.26250
892    393.93750
893    395.67500
894    392.30000
895    395.50000
Length: 896, dtype: float64

In [366]:
df_sc = pd.DataFrame(data = {'班级': df_s.班级, '姓名':df_s.姓名,
                          '总分': list(zcj())},
                  index = df_s.index)


df_sc

班级   姓名         总分
0     1   吴刚  371.94375
1     1   卢楠  395.54375
2     1  唐秀兰  391.28125
3     1   张刚  395.83125
4     1   姜洋  381.65000
..   ..  ...        ...
891  11  申建国  376.26250
892  11   裴勇  393.93750
893  11   王文  395.67500
894  11   夏刚  392.30000
895  11  权玉珍  395.50000

[896 rows x 3 columns]

In [369]:
df_sc[["班级","姓名","总分"]].nlargest(10,"总分")

班级   姓名         总分
598   8   王想  427.20000
163   3   黄萍  413.24375
503   7   黄文  413.00000
447   6   黎玉  412.13750
118   2  王淑英  410.63125
186   3   慕阳  410.62500
879  11  杨凤兰  410.47500
80    1   张欢  410.47500
500   7   吕雪  410.18750
289   4  孙桂珍  409.64375

### 4、
请统计1班到8班文理科（物化生为理科，政史地为文科）期末考试总分前5的学生，结果格式如下，括号内的为选科分数

In [191]:
pd.DataFrame(
    {
        "1班（文）": ["王大锤：历史（102）"]+["..."]* 4,
        "1班（理）": ["..."]* 5,
        "2班（文）": ["..."]* 5,
        "...": ["..."]* 5,
        "8班（理）": ["..."]* 5,
    }
) # 王大锤：历史（102）只是举个例子，表示结果字符串需要按照这个格式来写


1班（文） 1班（理） 2班（文）  ... 8班（理）
0  王大锤：历史（102）   ...   ...  ...   ...
1          ...   ...   ...  ...   ...
2          ...   ...   ...  ...   ...
3          ...   ...   ...  ...   ...
4          ...   ...   ...  ...   ...

In [370]:
df = pd.read_csv('data/supplement/ex2/期末考试成绩.csv')#读取表格


In [380]:
df1=df.groupby(["班级"]).size()
df2 = df1[:8].sum()
df2

681

In [385]:
df3 = df[0:df2]
df3

班级   姓名  选科   语文  数学   英语   科目
0     1   吴刚  地理   83  51  103  102
1     1   卢楠  物理  113  81   95  102
2     1  唐秀兰  历史  111  99   86  115
3     1   张刚  化学  111  84   87  108
4     1   姜洋  历史   96  85   84   96
..   ..  ...  ..  ...  ..  ...  ...
676   8   陈玲  化学   90  79   87   95
677   8   何成  物理  117  68   92  112
678   8   封军  政治   77  78   87  101
679   8   邓瑜  生物   87  87   78   86
680   8   陈慧  地理   96  77   96  102

[681 rows x 7 columns]

In [386]:
sc = df3.语文+df3.数学+df3.英语+df3.科目
df3.insert(loc=7, column='总分', value=list(sc))
df3

班级   姓名  选科   语文  数学   英语   科目   总分
0     1   吴刚  地理   83  51  103  102  339
1     1   卢楠  物理  113  81   95  102  391
2     1  唐秀兰  历史  111  99   86  115  411
3     1   张刚  化学  111  84   87  108  390
4     1   姜洋  历史   96  85   84   96  361
..   ..  ...  ..  ...  ..  ...  ...  ...
676   8   陈玲  化学   90  79   87   95  351
677   8   何成  物理  117  68   92  112  389
678   8   封军  政治   77  78   87  101  343
679   8   邓瑜  生物   87  87   78   86  338
680   8   陈慧  地理   96  77   96  102  371

[681 rows x 8 columns]

### 5、
学生成绩的稳定性可以用每次考试在全年级相同选科学生中的总分排名标准差来度量，请计算每个班级的各科学生成绩稳定性的均值，结果格式如下：

In [ ]:
pd.DataFrame(
    np.random.rand(11, 6),
    index=pd.Index(range(1, 12), name="班级"),
    columns=pd.Index(
        ["物理", "化学", "生物", "历史", "地理", "政治"],
        name="选科",
    )
)

# Ex3：统计商品的审核情况
在data/supplement/ex3中存放了两个有关商品审核的信息表，“商品信息.csv”中记录了每个商品的ID号，唯一的识别码以及商品所属的类别，“申请与审核记录.csv”中记录了每个商品的审核信息。已知商品的审核流程如下：由申请人发起商品审核的申请，然后由审核人审核，审核的结果包括通过与不通过两种情况，若商品不通过审核则可以由另一位申请人再次发起申请，直到商品的审核通过。

In [399]:
df_info = pd.read_csv('data/supplement/ex3/商品信息.csv')

df_info.head()

ID号      识别码  类别
0  ID 000001  CRtXJUK  T1
1  ID 000002  RGSxifC  Q1
2  ID 000003  AboduTp  S1
3  ID 000004  zlpUeMl  S2
4  ID 000005  IVQqhIK  S3

In [396]:
df_info.shape

(26832, 3)

In [389]:
df_record = pd.read_csv('data/supplement/ex3/申请与审核记录.csv')

df_record.head()

ID号         申请人        申请时间         审核人        审核时间   结果
0  ID 000001  \#+3((52\{  2020-04-19  ~1=6\*183|  2020-05-03  未通过
1  ID 000001  8@75[1|2\*  2020-05-10  15![3\({59  2020-07-17  未通过
2  ID 000001  }!7)(#^0*7  2020-07-28  3`}04}%@75  2020-08-23   通过
3  ID 000002  |*{20#9|}5  2020-01-05  ={`8]03*4+  2020-03-09  未通过
4  ID 000002  4~6%)455`[  2020-03-14  =$-36[)|8]  2020-04-21  未通过

### 1、
有多少商品最终通过审核？


In [418]:
df1= df_record.groupby(["结果"]).size()
a = df1["通过"]
a

10848

In [419]:
b = df_info.shape[0]
b

26832

In [420]:
int(b)-int(a)

15984

### 2、
各类别商品的通过率分别为多少？


In [421]:
df_info

ID号      识别码  类别
0      ID 000001  CRtXJUK  T1
1      ID 000002  RGSxifC  Q1
2      ID 000003  AboduTp  S1
3      ID 000004  zlpUeMl  S2
4      ID 000005  IVQqhIK  S3
...          ...      ...  ..
26827  ID 026828  RWVzlsn  S2
26828  ID 026829  GetBGJp  T1
26829  ID 026830  AXOfdqd  T2
26830  ID 026831  oBnJLra  T2
26831  ID 026832  kMekGpT  Q1

[26832 rows x 3 columns]

In [447]:
df_record

ID号         申请人        申请时间         审核人        审核时间   结果
0       ID 000001  \#+3((52\{  2020-04-19  ~1=6\*183|  2020-05-03  未通过
1       ID 000001  8@75[1|2\*  2020-05-10  15![3\({59  2020-07-17  未通过
2       ID 000001  }!7)(#^0*7  2020-07-28  3`}04}%@75  2020-08-23   通过
3       ID 000002  |*{20#9|}5  2020-01-05  ={`8]03*4+  2020-03-09  未通过
4       ID 000002  4~6%)455`[  2020-03-14  =$-36[)|8]  2020-04-21  未通过
...           ...         ...         ...         ...         ...  ...
147495  ID 026832  -`$~=9+&`)  2020-02-23  8`32#~-+)}  2020-03-19  未通过
147496  ID 026832  0()##{3!~~  2020-03-25  *0131$+7*$  2020-05-01  未通过
147497  ID 026832  |\7`+7_2-|  2020-05-09  \[=2\|\_1|  2020-05-12  未通过
147498  ID 026832  +97~|)]+7`  2020-05-13  ~}!*494&8`  2020-06-19  未通过
147499  ID 026832  431+!&3]08  2020-06-27  }]]|_=8\%0  2020-08-13  未通过

[147500 rows x 6 columns]

In [449]:
df1 = df_record.merge(df_info, on='ID号', how='left')#左连接
df1

ID号         申请人        申请时间         审核人        审核时间   结果  \
0       ID 000001  \#+3((52\{  2020-04-19  ~1=6\*183|  2020-05-03  未通过   
1       ID 000001  8@75[1|2\*  2020-05-10  15![3\({59  2020-07-17  未通过   
2       ID 000001  }!7)(#^0*7  2020-07-28  3`}04}%@75  2020-08-23   通过   
3       ID 000002  |*{20#9|}5  2020-01-05  ={`8]03*4+  2020-03-09  未通过   
4       ID 000002  4~6%)455`[  2020-03-14  =$-36[)|8]  2020-04-21  未通过   
...           ...         ...         ...         ...         ...  ...   
147495  ID 026832  -`$~=9+&`)  2020-02-23  8`32#~-+)}  2020-03-19  未通过   
147496  ID 026832  0()##{3!~~  2020-03-25  *0131$+7*$  2020-05-01  未通过   
147497  ID 026832  |\7`+7_2-|  2020-05-09  \[=2\|\_1|  2020-05-12  未通过   
147498  ID 026832  +97~|)]+7`  2020-05-13  ~}!*494&8`  2020-06-19  未通过   
147499  ID 026832  431+!&3]08  2020-06-27  }]]|_=8\%0  2020-08-13  未通过   

            识别码  类别  
0       CRtXJUK  T1  
1       CRtXJUK  T1  
2       CRtXJUK  T1  
3       RGSxifC  Q1  
4       RGSxifC  Q1  
...         ...  ..  
147495  kMekGpT  Q1  
147496  kMekGpT  Q1  
147497  kMekGpT  Q1  
147498  kMekGpT  Q1  
147499  kMekGpT  Q1  

[147500 rows x 8 columns]

In [482]:
gb = df1.groupby(['类别','结果'])
r1 = gb.size()
r1

类别  结果 
Q1  未通过    19153
    通过      1494
Q2  未通过    20010
    通过      1613
S1  未通过    19552
    通过      1538
S2  未通过    19162
    通过      1548
S3  未通过    19529
    通过      1582
T1  未通过    19324
    通过      1509
T2  未通过    19922
    通过      1564
dtype: int64

In [483]:
gb2 = df1.groupby(['类别'])
r2 = gb2.size()
r2

类别
Q1    20647
Q2    21623
S1    21090
S2    20710
S3    21111
T1    20833
T2    21486
dtype: int64

### 3、
对于类别为“T1”且最终状态为通过的商品，平均审核次数为多少？


In [484]:
df1

ID号         申请人        申请时间         审核人        审核时间   结果  \
0       ID 000001  \#+3((52\{  2020-04-19  ~1=6\*183|  2020-05-03  未通过   
1       ID 000001  8@75[1|2\*  2020-05-10  15![3\({59  2020-07-17  未通过   
2       ID 000001  }!7)(#^0*7  2020-07-28  3`}04}%@75  2020-08-23   通过   
3       ID 000002  |*{20#9|}5  2020-01-05  ={`8]03*4+  2020-03-09  未通过   
4       ID 000002  4~6%)455`[  2020-03-14  =$-36[)|8]  2020-04-21  未通过   
...           ...         ...         ...         ...         ...  ...   
147495  ID 026832  -`$~=9+&`)  2020-02-23  8`32#~-+)}  2020-03-19  未通过   
147496  ID 026832  0()##{3!~~  2020-03-25  *0131$+7*$  2020-05-01  未通过   
147497  ID 026832  |\7`+7_2-|  2020-05-09  \[=2\|\_1|  2020-05-12  未通过   
147498  ID 026832  +97~|)]+7`  2020-05-13  ~}!*494&8`  2020-06-19  未通过   
147499  ID 026832  431+!&3]08  2020-06-27  }]]|_=8\%0  2020-08-13  未通过   

            识别码  类别  
0       CRtXJUK  T1  
1       CRtXJUK  T1  
2       CRtXJUK  T1  
3       RGSxifC  Q1  
4       RGSxifC  Q1  
...         ...  ..  
147495  kMekGpT  Q1  
147496  kMekGpT  Q1  
147497  kMekGpT  Q1  
147498  kMekGpT  Q1  
147499  kMekGpT  Q1  

[147500 rows x 8 columns]

### 4、
是否存在商品在上一次审核未完成时就提交了下一次审核申请？


### 5、
请对所有审核通过的商品统计第一位申请人和最后一位审核人的信息，返回格式如下：

In [ ]:
pd.DataFrame(
    {
        "ID号": ["ID 000001"]+["..."]*3,
        "类别":["T1"]+["..."]*3,
        "申请人":["\#+3((52\{"]+["..."]*3,
        "审核人":["3`}04}%@75"]+["..."]*3
    },
    index=[1,2,3,"..."]
)

###### 提示
groupby对象上也定义了head和tail方法。